# Install keepalived
- name: Remove keepalived
  yum:
    name: keepalived
    state: absent

- name: Install keepalived
  yum:
    name: keepalived
    state: latest

- name: Enable keepalived server
  systemd:
    name: keepalived
    state: started
    enabled: yes

- name: Create a directory for the  log file
  file: path={{ item }} state=directory owner=root group=root
  with_items:
    - "{{ log_dir }}"

- name: Config keepalived file for the log of keepalived
  lineinfile:
    path: /etc/sysconfig/keepalived
    regexp: "^KEEPALIVED_OPTIONS="
    line: 'KEEPALIVED_OPTIONS="-D -S 0"'

- name: Add monitor log file path for the log of keepalived
  lineinfile:
    path: /etc/rsyslog.conf
    line: "{{ item }}"
    insertafter: EOF
    state: present
  with_items:
    - "# Save keepalived.log"
    - "{{ log_channel }}.*       {{ log_dir }}/keepalived.log"
  notify: restart rsyslog

- name: Copy script file
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0744
  with_items:
    - { src: 'check_haproxy.sh', dest: '/etc/keepalived' }
    - { src: 'check_proxysql.sh', dest: '/etc/keepalived' }
  run_once: True

- name: Rendering the logrotate file and bash script file
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0744
  with_items:
    - { src: 'keepalived.j2', dest: '/etc/logrotate.d/keepalived' }
    - { src: 'notify_action.sh.j2', dest: '/etc/keepalived/notify_action.sh' }

- name: Register the unicast_peer for keepalived parameter file
  shell: "cat /etc/hosts | grep {{ proxysql_or_haproxy }} | grep -v {{ ansible_default_ipv4.address }} | awk '{printf $1}'"
  register: unicast_peer

- name: Rendering keepalived parameter file
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    owner: root
    group: root
    mode: 0644
  notify: restart keepalived

- name: Add log polling task schedule for keepalived
  cron:
    name: "keepalive logrotate"
    minute: "50"
    hour: "23"
    job: "/usr/sbin/logrotate -vf -s /var/lib/logrotate/logrotate.status /etc/logrotate.d/keepalived > /dev/null"